server:
  port: 8099

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password: alaa2001..
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  eureka:
    client:
      serviceUrl:

        defaultZone: http://localhost:8761/eureka/


security:
  jwt:
    secret-key: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    expiration-time: 3600000