server:
  port: 8082

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/task_db?createDatabaseIfNotExist=true
    username: root
    password: alaa2001..
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  eureka:
    client:
      serviceUrl:

        defaultZone: http://localhost:8761/eureka/
